@Backend_HostAddress = http://localhost:5286

GET {{Backend_HostAddress}}/test/
Accept: application/json

###

GET {{Backend_HostAddress}}/brand/

###

POST {{Backend_HostAddress}}/brand/
Content-Type: application/json

{
    "name":"Una marca nueva"
}

###

PUT {{Backend_HostAddress}}/brand/7
Content-Type: application/json

{
    "name": "marca editada"
}

###

DELETE {{Backend_HostAddress}}/brand/7